### ISSUE TITLE
 Docker secrets?

### ISSUE THREAD

**Issue by jathek** [concision/docker-windscribe-socks-server#7]
Any plans to implement [docker secrets](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images) for the username and password? Ideally I could use secrets for the u/p for both Windscribe and the proxy.

**Comment by concision** [comment]
I have pushed a new version [`concisions/windscribe-socks-server:0.3.2`](https://hub.docker.com/layers/concisions/windscribe-socks-server/0.3.2/images/sha256-d5b0e77b879f92247aa42d4c58f7118e0a8b970823c95b60885f062cdbd35d08?context=explore) that has support for Docker secrets.

I have updated some notes on the [development branch's documentation](https://github.com/concision/docker-windscribe-socks-server/tree/development#docker-compose):

> An `.env` file containing all environment variable configuration can be passed as a [Docker secret](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose) file using the key `windscribe_server`. Uncomment the relevant section in the [`docker-compose.yml`](https://github.com/concision/docker-windscribe-socks-server/blob/development/docker-compose.yml) file template. Configured Docker secrets take precedence over environment variables.

Let me know if this works for you. If so, I will publish it to `latest` and close this issue.

**Comment by jathek** [comment]
I'm getting the error `2020-12-09 22:55:28 ERR [WINDSCRIBE] Unset Windscribe username; ensure that the environment variable $WINDSCRIBE_USERNAME is set properly` in the logs. Below is compose and the format of the secret I'm passing. Previously this compose worked fine with all the variables uncommented. Should I be mapping this secret somewhere?

Troubleshooting:
- I thought there might be a problem mixing and matching the secret with some environment variables set directly in compose, so I also tried commenting out the entire environment section, but I get the same error. Ideally splitting variables between compose and the secret should work because setting the non-private secrets is easier to manage in compose.
- I thought perhaps setting the environment variables in compose and then letting the secret overwrite them would work, so I set all the username/password variables to "environ" in compose. The secret does not take precedence though, I just get errors about the container not being able to log into Windscribe with the username and password provided.
```
  # windscribe 2 vpn + proxy  - Montreal             Expo 67
  vpn-ws2:
    container_name: vpn-ws2
    image: concisions/windscribe-socks-server:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      t2_proxy:
    ports:
      - 42022:1080
    tmpfs:
      - /etc/windscribe:exec
    secrets:
      - windscribe_server
    environment:
      WINDSCRIBE_DNS: "${WINDSCRIBE_DNS:-1.1.1.1}"
      # WINDSCRIBE_USERNAME: "$WINDSCRIBE_USERNAME"
      # WINDSCRIBE_PASSWORD: "$WINDSCRIBE_PASSWORD"
      WINDSCRIBE_LOCATION: "Expo 67"
      # SOCKS_USERNAME_1: "${PROXY_USERNAME:-}"
      # SOCKS_PASSWORD_1: "${PROXY_PASSWORD:-}"
```
```
WINDSCRIBE_USERNAME=windscribeusername
WINDSCRIBE_PASSWORD=windscribepassword
SOCKS_USERNAME_1=proxyusername
SOCKS_PASSWORD_1=proxypassword
```
